// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLAf00JZkJ7Gs5lH8mEXLwlu5MGSjbNo',
    appId: '1:491486859612:web:8e8908b4a289f56790f199',
    messagingSenderId: '491486859612',
    projectId: 'ironbit-3aacc',
    authDomain: 'ironbit-3aacc.firebaseapp.com',
    storageBucket: 'ironbit-3aacc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAugPZtfvA6Kc6k0fRbBTkhuBNlXBKGLFs',
    appId: '1:491486859612:android:2f3887e5aa17457090f199',
    messagingSenderId: '491486859612',
    projectId: 'ironbit-3aacc',
    storageBucket: 'ironbit-3aacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSv6j4AWaP4W-xxK0J9TS3NXuqGr7t8pI',
    appId: '1:491486859612:ios:5fe6ab350d8969e890f199',
    messagingSenderId: '491486859612',
    projectId: 'ironbit-3aacc',
    storageBucket: 'ironbit-3aacc.firebasestorage.app',
    iosBundleId: 'com.example.studentTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSv6j4AWaP4W-xxK0J9TS3NXuqGr7t8pI',
    appId: '1:491486859612:ios:5fe6ab350d8969e890f199',
    messagingSenderId: '491486859612',
    projectId: 'ironbit-3aacc',
    storageBucket: 'ironbit-3aacc.firebasestorage.app',
    iosBundleId: 'com.example.studentTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLAf00JZkJ7Gs5lH8mEXLwlu5MGSjbNo',
    appId: '1:491486859612:web:3f0ebcb68709765690f199',
    messagingSenderId: '491486859612',
    projectId: 'ironbit-3aacc',
    authDomain: 'ironbit-3aacc.firebaseapp.com',
    storageBucket: 'ironbit-3aacc.firebasestorage.app',
  );
}
